logging:
    file: /opt/batch/LocationUpdater/logs/dw.log
spring:
    jackson:
            serialization.indent_output: true
    main:
        web-environment: false
    datasource:
        driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: default
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
fleet:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: default
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
        hibernate:
            dialect: org.hibernate.dialect.SQLServer2012Dialect
email:
    google:
        api: jason-liu@plantsyncrhonizer.iam.gserviceaccount.com
plants:
    sheet:
        id: 16VdfZZNiHPtd9f6MkXjOhXMrvXtTBRZ2wazjracgYkw
        range: Plants!A1:AU

